import ConnectionLinks from '../equipmentImages/ConnectionLinks';
import { imageViews } from '../equipmentImages/model';
import { useState } from 'react';
import { useFacility, useFacilityEditor } from '../facility';
import { PageLink } from '../navigation/AppShell';
import { documentSource } from '../lib/documentCatalog';
import { renderMarkdown } from '../lib/markdown';
import { useWorkRecords } from '../repairs/useWork';
import Troubleshooting from '../troubleshooting/Troubleshooting';

export function EquipmentPage(){
  const pkg=useFacility(),params=new URLSearchParams(location.search);
  const [query,setQuery]=useState(params.get('q')??'');const q=query.toLowerCase().trim();
  const assets=pkg.assets.filter(a=>[a.name,a.id,a.description,a.manufacturer.value,a.model.value].join(' ').toLowerCase().includes(q));
  return <main className="slate-workspace"><label>Search equipment<input value={query} onChange={e=>{setQuery(e.target.value);const p=new URLSearchParams(location.search);p.set('q',e.target.value);history.replaceState(history.state,'','?'+p);}} placeholder="Name, model, or equipment number"/></label><div className="slate-list">{assets.map(a=><PageLink key={a.id} page="machine" details={{asset:a.id}} className="slate-card"><span>{a.name}<small>{a.line || pkg.areas.find(area=>area.id===a.areaId)?.name} · {a.id}</small></span><span aria-hidden="true">›</span></PageLink>)}</div>{!assets.length&&<p>No equipment matches. Try a familiar name or choose the map.</p>}
    {q&&<><h2>Related documents</h2><div className="slate-list">{pkg.documents.filter(d=>(d.title+' '+d.category).toLowerCase().includes(q)).slice(0,12).map(d=><PageLink key={d.id} page="machine" details={{asset:d.assetId,section:'manuals',doc:d.id}} className="slate-card">{d.title}</PageLink>)}</div><h2>Related parts</h2><div className="slate-list">{(pkg.facility.inventory?.parts??[]).filter(p=>(p.name+' '+p.partNumber+' '+p.description).toLowerCase().includes(q)).slice(0,12).map(p=><PageLink key={p.id} page="inventory" details={{part:p.id,q:query}} className="slate-card">{p.name}</PageLink>)}</div></>}
    <div className="slate-actions"><PageLink page="map" className="slate-card">Facility Map</PageLink><PageLink page="lines" className="slate-card">Production lines</PageLink><PageLink page="assets" details={{section:'devices'}} className="slate-card">Devices & areas</PageLink></div></main>;
}
const sections=[['overview','Overview'],['troubleshooting','Troubleshooting'],['history','Repair history'],['electrical','Electrical'],['controls','Controls'],['parts','Parts'],['manuals','Manuals'],['photos','Photos']] as const;
export default function MachinePage(){
  const pkg=useFacility(),editor=useFacilityEditor(),params=new URLSearchParams(location.search),assetId=params.get('asset')??'',section=params.get('section')??'',workId=params.get('work')??'';
  const asset=pkg.assets.find(a=>a.id===assetId);const work=useWorkRecords();
  if(!asset)return <main className="slate-workspace"><p>This machine is not in this facility.</p><PageLink page="assets">Choose equipment →</PageLink></main>;
  const visualCabinet = imageViews(pkg,assetId)[0] ?? pkg.featureConfig.imageViews?.find(v => v.machineId === assetId);
  const documents=pkg.documents.filter(d=>d.assetId===assetId),selectedDoc=documents.find(d=>d.id===params.get('doc'));
  const evidenceIds=new Set([...documents.flatMap(d=>d.evidenceIds),...asset.facts.flatMap(f=>f.value.evidenceIds),...pkg.components.filter(c=>c.parentId===assetId).flatMap(c=>c.evidenceIds)]);
  const photos=pkg.evidence.filter(e=>evidenceIds.has(e.id)&&['PHOTO','NAMEPLATE'].includes(e.type)&&e.access==='PUBLIC_APP');
  return <main className="slate-workspace" data-testid="machine-workspace">
    {workId&&<PageLink page="repair" details={{work:workId,asset:assetId}} className="slate-text-link">← Return to this repair</PageLink>}<small>{asset.id}</small>{visualCabinet&&<PageLink page="cabinet" details={{asset:visualCabinet.assetId,image:visualCabinet.id}} className="page-primary">Explore cabinet photos</PageLink>}{!section&&/climax/i.test(asset.name+" "+asset.manufacturer.value)&&<PageLink page="machine" details={{asset:assetId,section:"troubleshooting"}} className="page-primary">Why won’t it run?</PageLink>}{!section?<><PageLink page="repair" details={{asset:assetId,work:workId}} className="page-primary">{workId?'Resume repair':'Start a repair'}</PageLink><div className="slate-list">{sections.map(([id,label])=><PageLink key={id} page="machine" details={{asset:assetId,work:workId,section:id}} className="slate-card">{label}<span aria-hidden="true">›</span></PageLink>)}</div></>:<>
    {!selectedDoc&&<h2>{sections.find(([id])=>id===section)?.[1]??'Machine information'}</h2>}
    {section==='overview'&&<><ConnectionLinks entityId={assetId}/><p>{asset.description}</p><dl className="slate-card"><dt>Manufacturer</dt><dd>{asset.manufacturer.value||'Not recorded'}</dd><dt>Model</dt><dd>{asset.model.value||'Not recorded'}</dd><dt>Serial number</dt><dd>{asset.serialNumber.value||'Not recorded'}</dd><dt>Record status</dt><dd>{asset.verificationStatus.replaceAll('_',' ')}</dd></dl><PageLink page="asset" details={{asset:assetId,work:workId,tab:'record'}} className="slate-card">Full equipment record & evidence</PageLink><PageLink page="maintenance" details={{asset:assetId,work:workId}} className="slate-card">Service, utilities & production details</PageLink>{asset.unknowns.length>0&&<details><summary>Information to confirm</summary><ul>{asset.unknowns.map(u=><li key={u}>{u}</li>)}</ul></details>}</>}
    {section==='troubleshooting'&&<>{/climax/i.test(asset.name+' '+asset.manufacturer.value)?<Troubleshooting assetId={assetId}/>:<PageLink page="repair" details={{asset:assetId,work:workId,guided:'1'}} className="page-primary">Work through a problem</PageLink>}<PageLink page="relationships" details={{asset:assetId,work:workId}} className="slate-card">Documented connections</PageLink><PageLink page="machine" details={{asset:assetId,work:workId,section:'history'}} className="slate-card">Previous repairs</PageLink></>}
    {section==='history'&&<><div className="slate-list">{(asset.production?.service??[]).map(s=><article key={s.id} className="slate-card"><h3>{s.symptom||'Service record'}</h3><small>{s.date}</small><p>{s.observation}</p><p>{s.action}</p><p>{s.spareParts}</p><p>{s.task}</p></article>)}</div>{!asset.production?.service.length&&<p>No applied repair history is recorded for this machine.</p>}<h3>Your work in progress</h3>{work.records.filter(w=>w.assetId===assetId).map(w=><PageLink key={w.id} page="repair" details={{asset:assetId,work:w.id}} className="slate-card">{w.summary.problem||w.entries[0]?.text||'Open repair'}<small>{w.transport}</small></PageLink>)}</>}
    {['electrical','controls'].includes(section)&&<>{assetId===pkg.featureConfig.featuredCabinetAssetId&&<PageLink page="cabinet" details={{asset:assetId,work:workId}} className="page-primary">Open cabinet drawing</PageLink>}<div className="slate-list">{pkg.components.filter(c=>c.parentId===assetId&&(section==='electrical'?['VFD','SERVO_DRIVE','POWER_SUPPLY','DISCONNECT','CONTROL_CABINET'].includes(c.type):['REMOTE_IO','PLC','DIGITAL_INPUT','DIGITAL_OUTPUT','ANALOG_INPUT','ANALOG_OUTPUT','RELAY_OUTPUT','CONTROLLER','ELECTRONIC_CAM'].includes(c.type))).map(c=><PageLink key={c.id} page="component" details={{asset:assetId,work:workId,component:c.id}} className="slate-card">{c.label}<small>{c.type} · {c.verificationStatus.replaceAll('_',' ')}</small></PageLink>)}</div><PageLink page="maintenance" details={{asset:assetId,work:workId,section:'electrical'}} className="slate-card">Electrical field records</PageLink><PageLink page="relationships" details={{asset:assetId,work:workId}} className="slate-card">Power, controls & connected equipment</PageLink>{assetId===pkg.featureConfig.featuredMachineAssetId&&<PageLink page="wulftec" details={{asset:assetId,work:workId}} className="slate-card">Machine assemblies</PageLink>}</>}
    {section==='parts'&&<><PageLink page="inventory" details={{asset:assetId,work:workId}} className="page-primary">Find compatible spares</PageLink><PageLink page="repair" details={{asset:assetId,work:workId}} className="slate-card">Record parts used in a repair</PageLink></>}
    {section==='manuals'&&(selectedDoc?<><h2>{selectedDoc.title}</h2><PageLink page="documents" details={{asset:assetId,doc:selectedDoc.id,work:workId}} className="page-primary">Open original document & attachments</PageLink><p className="slate-status">{selectedDoc.verificationStatus.replaceAll('_',' ')}</p><article className="slate-card" dangerouslySetInnerHTML={{__html:renderMarkdown(documentSource(selectedDoc.path) ?? 'Original document content is unavailable. Open the source library to inspect its evidence.')}}/></>:<div className="slate-list">{documents.length?documents.map(d=><PageLink key={d.id} page="machine" details={{asset:assetId,work:workId,section:'manuals',doc:d.id}} className="slate-card">{d.title}<small>{d.category}</small></PageLink>):<p>No manuals are recorded. Add the original file for review.</p>}</div>)}
    {section==='photos'&&<>{photos.length?photos.map(p=><figure key={p.id} className="slate-card"><img src={p.pathOrUrl.startsWith('http')?p.pathOrUrl:p.pathOrUrl.startsWith(import.meta.env.BASE_URL)?p.pathOrUrl:import.meta.env.BASE_URL+p.pathOrUrl.replace(/^\//,'')} alt={p.title} loading="lazy"/><figcaption>{p.title}</figcaption></figure>):<p>No linked public photographs are recorded.</p>}<PageLink page="evidence" details={{asset:assetId,work:workId}} className="slate-card">Attached files & original evidence</PageLink><PageLink page="repair" details={{asset:assetId,work:workId}} className="page-primary">Add a photo for review</PageLink></>}
    </>}{editor.currentUser?.role==='admin'&&section==='overview'&&<PageLink page="manage" details={{asset:assetId,work:workId}} className="slate-text-link">Edit equipment record →</PageLink>}
  </main>;
}
