"""Photo-to-stock workflow in isolated authenticated browser fixtures only."""
import io
import json
from PIL import Image, ImageDraw, ImageFont


def exercise_inventory(page, base, label, screenshot, geometry):
    page.goto(base+'?page=inventory', wait_until='networkidle')
    page.get_by_role('button', name='Take photo / Add part', exact=True).click()
    page.get_by_label('Name / description', exact=True).fill('Synthetic inventory contactor')
    page.get_by_label('Manufacturer part number', exact=True).fill('TEST-INVENTORY-24')
    page.get_by_label('Manufacturer', exact=True).fill('Synthetic manufacturer')
    page.get_by_label('Ratings / specifications', exact=True).fill('24 V coil fixture only')
    page.get_by_label('Building', exact=True).fill('Synthetic building')
    page.get_by_label('Shelf', exact=True).fill('TEST-SHELF-7')
    page.get_by_label('Photo role', exact=True).select_option('Label')
    image = io.BytesIO()
    label_image = Image.new('RGB', (1000,240), 'white')
    font_path = 'C:/Windows/Fonts/arial.ttf' if __import__('os').name == 'nt' else '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
    ImageDraw.Draw(label_image).text((30,50), 'Model: TEST123', fill='black', font=ImageFont.truetype(font_path, 60))
    label_image.save(image, format='PNG')
    page.get_by_label('Upload part photos', exact=True).set_input_files({'name':'synthetic-inventory-label.png','mimeType':'image/png','buffer':image.getvalue()})
    page.get_by_text('Photos attached.', exact=False).wait_for()
    page.get_by_role('button', name='Read label text', exact=True).click()
    page.get_by_role('button', name='Use model: TEST123', exact=True).wait_for(timeout=60000)
    page.get_by_role('button', name='Use model: TEST123', exact=True).click()
    assert page.get_by_label('Model', exact=True).input_value() == 'TEST123'
    assert not page.get_by_label('I compared the identity fields with the source', exact=True).is_checked()
    page.get_by_label('Visible label text / unverified extraction', exact=True).fill('TEST-INVENTORY-24 24V synthetic label')
    page.get_by_label('I compared the identity fields with the source', exact=True).check()
    geometry(page)
    page.get_by_role('button', name='Read label text', exact=True).scroll_into_view_if_needed()
    screenshot(page, f'{label}-inventory-add-photo')
    page.get_by_role('button', name='Save part', exact=True).click()
    page.get_by_role('button', name='Open part / stock actions', exact=True).click()
    detail = page.get_by_role('region', name='Selected part')
    page.get_by_label('Quantity', exact=True).fill('5')
    page.get_by_label('Work note / reason', exact=True).fill('Opening stock in isolated browser fixture')
    page.get_by_role('button', name='Record stock movement', exact=True).click()
    page.get_by_text('5 each available', exact=False).wait_for()
    page.get_by_label('Machine to link', exact=True).select_option('L2-CC-001')
    page.get_by_label('Compatibility status', exact=True).select_option('Verified spare')
    page.get_by_label('Source / verification reason', exact=True).fill('Synthetic fixture compatibility source')
    page.get_by_role('button', name='Save machine compatibility', exact=True).click()
    page.get_by_text('Verified spare', exact=False).first.wait_for()
    page.goto(base+'?page=asset&asset=L2-CC-001', wait_until='networkidle')
    page.get_by_role('link', name='Find a part / compatible spares', exact=True).click()
    assert page.get_by_label('Machine', exact=True).input_value() == 'L2-CC-001'
    page.get_by_role('button', name='Open part / stock actions', exact=True).click()
    page.get_by_label('Action', exact=True).select_option('Issue / install')
    page.get_by_label('Quantity', exact=True).fill('2')
    page.get_by_label('Work note / reason', exact=True).fill('Synthetic installation check')
    page.get_by_role('button', name='Record stock movement', exact=True).click()
    page.get_by_text('3 each available', exact=False).wait_for()
    page.get_by_label('Action', exact=True).select_option('Verify count')
    page.get_by_label('Actual total count', exact=True).fill('3')
    page.get_by_label('Work note / reason', exact=True).fill('Synthetic physical count confirmed')
    page.get_by_role('button', name='Record stock movement', exact=True).click()
    page.get_by_role('region', name='Selected part').locator('p').filter(has_text='Synthetic physical count confirmed').wait_for()
    geometry(page)
    screenshot(page, f'{label}-inventory-stock-history')
    page.get_by_role('button', name='Activity', exact=True).click()
    assert 'Synthetic installation check' in page.locator('.inventory-workspace').inner_text()
    page.get_by_role('button', name='Advanced', exact=True).click()
    with page.expect_download() as download:
        page.get_by_role('button', name='Download backup with inventory photos', exact=True).click()
    backup = json.loads(open(download.value.path(), encoding='utf-8').read())
    part = next(p for p in backup['plant']['facility']['inventory']['parts'] if p['partNumber']=='TEST-INVENTORY-24')
    assert len(part['ledger']) == 3
    assert any(a['id']==part['photos'][0]['id'] and a['dataUrl'].startswith('data:image/png') for a in backup['attachments'])
    page.goto(base+'?facilityId=test-facility&page=inventory', wait_until='networkidle')
    assert 'Synthetic inventory contactor' not in page.locator('.inventory-workspace').inner_text()
    page.goto(base+'?page=inventory', wait_until='networkidle')
    page.get_by_text('3 each available', exact=False).wait_for()
