import type { GuideContext, GuideMessage, GuidePersonality } from './guideTypes';
import { nextGuideMessage } from './guideRules';
export const guideTopics = [
  ['next', 'Next best step'], ['electrical', 'Electrical facts'], ['trace', 'Trace connections'],
  ['evidence', 'Photos & PDFs'], ['verification', 'What’s verified?'], ['work', 'Maintenance tasks'],
  ['map', 'Map & layers'], ['reports', 'Reports & backups'],
] as const;
export type GuideTopic = typeof guideTopics[number][0];
export function answerGuide(topic: GuideTopic, c: GuideContext, personality: GuidePersonality, publicationEnabled = false): GuideMessage {
  if (topic === 'next') return nextGuideMessage(c, personality);
  const asset = c.assetId ?? 'the selected equipment';
  const answers: Record<Exclude<GuideTopic, 'next'>, GuideMessage> = {
    electrical: { id: 'kb-electrical', title: 'Read the label. Keep the source.', body: c.assetId ? 'Structured electrical gaps: ' + (c.electricalGaps?.join(', ') || 'none among the checked labels') + '. A missing entry does not prove a missing device. Field-sheet values without per-field verification are UNVERIFIED. Follow site LOTO and electrical safe-work procedures; this is documentation guidance.' : 'Select equipment to inspect its electrical entries. Never infer voltage, supply or isolation from a symbol.', animation: 'warning', actions: [{ id: 'capture-electrical', label: 'Open electrical field sheet', primary: true }] },
    trace: { id: 'kb-trace', title: 'A line on a map is not a feed.', body: c.assetId ? asset + ' has ' + c.relationshipCount + ' direct links. ' + c.upstreamCount + ' incoming and ' + c.downstreamCount + ' outgoing direct electrical/control dependencies are marked VERIFIED with evidence references. These counts do not establish operating state or an isolation boundary.' : 'Choose equipment to inspect direct connections. The troubleshooting workspace can follow recorded paths; absent feeds stay unknown.', animation: 'point', actions: [{ id: 'show-relationships', label: 'Open troubleshooting', primary: true }, { id: 'link-asset', label: 'Document a connection' }] },
    evidence: { id: 'kb-evidence', title: 'Future-you wants the photo.', body: (c.assetId ? asset + ' has ' + c.evidenceCount + ' distinct referenced evidence records. ' : '') + (publicationEnabled ? 'Public shared saves are enabled for this facility; new uploads in Attach evidence may be published. Check the uploader’s access notice before adding a file. ' : 'New uploads are LOCAL_ONLY in the current configuration. ') + 'The Genie never changes evidence access; LOCAL_ONLY evidence must remain excluded from automatic transport.', animation: 'point', actions: [{ id: 'attach-evidence', label: 'Open Attach evidence', primary: true }, { id: 'show-documents', label: 'Find existing documents' }] },
    verification: { id: 'kb-verification', title: 'Observed ≠ verified.', body: (c.assetId ? asset + ' is marked ' + c.verification + '. ' : '') + 'Each fact has its own state. FIELD_VERIFY needs field confirmation; INFERRED is an inference; DISPUTED retains a conflict. VERIFIED is a recorded status, not a live equipment check. Genie findings save as FIELD_VERIFY observations and never overwrite canonical facts.', animation: 'warning', actions: [{ id: 'review', label: 'Open review', primary: true }, { id: 'capture-note', label: 'Record an observation' }] },
    work: { id: 'kb-work', title: 'Leave a task, not a treasure hunt.', body: 'This app records service history and maintenance tasks in the equipment field sheet. It does not issue CMMS work orders. Record the symptom, observation, task and evidence; use your site’s work-order system for dispatch.', actions: [{ id: 'service', label: 'Open service / task records', primary: true }] },
    map: { id: 'kb-map', title: 'Put it where you found it.', body: 'Map layers control what is visible. Admins can use Edit map → Areas & shapes or Symbols to document rooms, walls, doors, stairs and equipment placement. Cursor / Pan moves the view. The compact Fit resets the drawing. Review and save edits explicitly.', animation: 'point', actions: [{ id: 'show-map', label: 'Open map', primary: true }] },
    reports: { id: 'kb-reports', title: 'Take the record with you.', body: 'Print an equipment field sheet for a walkdown, or use Plant database for an .iag backup. Documentation progress is weighted required-document completion; it does not measure safety or verification.', actions: [{ id: 'service', label: 'Open printable field sheet', primary: true }, { id: 'reports', label: 'Open backups' }] },
  };
  return answers[topic];
}
