import type { GuideContext, GuideMessage } from './guideTypes';

export const guideDialogue = {
  welcome: (): GuideMessage => ({ id: 'welcome', title: 'Facility Guide', body: 'I can point out what is documented, what is missing, and where to look next. I never fill in facts that are not in the facility record.', animation: 'enter', actions: [{ id: 'start-tour', label: 'Show me around', primary: true }, { id: 'show-map', label: 'Open map' }] }),
  map: (): GuideMessage => ({ id: 'map', title: 'Building layout', body: 'This is the real 2D facility plan. Select a labeled area or asset to inspect its documented record.', animation: 'point', target: '[data-guide-target="facility-map"]', actions: [{ id: 'show-assets', label: 'Next: assets', primary: true }] }),
  assets: (context: GuideContext): GuideMessage => ({ id: 'assets', title: context.assetId ?? 'Asset records', body: context.assetId ? `You are viewing ${context.assetId}. Blank or unknown fields stay visible as gaps until they are verified.` : 'Choose an asset to see its known facts, evidence, and open fieldwork items.', target: '[data-guide-target="asset-workspace"]', actions: [{ id: 'show-relationships', label: 'Trace relationships', primary: true }] }),
  relationships: (context: GuideContext): GuideMessage => ({ id: 'relationships', title: 'Documented relationships', body: context.assetId ? `Only recorded links for ${context.assetId} appear here. No upstream source will be implied when it is undocumented.` : 'Relationship traces show recorded links only. Missing upstream or downstream links remain missing.', target: '[data-guide-target="relationships"]', actions: [{ id: 'show-documents', label: 'Check documents', primary: true }] }),
  documents: (): GuideMessage => ({ id: 'documents', title: 'Evidence, not assumptions', body: 'Documents and photos support the asset record. An absent document is treated as a gap, not replaced with a guess.', target: '[data-guide-target="documents"]', actions: [{ id: 'show-map', label: 'Finish on map', primary: true }] }),
  cabinet: (): GuideMessage => ({ id: 'cabinet', title: 'Control cabinet walkthrough', body: 'Use the cabinet view to inspect documented devices and evidence. Device names and connections remain exactly as recorded.', target: '[data-guide-target="cabinet"]', actions: [{ id: 'show-relationships', label: 'Trace cabinet', primary: true }] }),
};
