import { useEffect, useMemo, useState } from 'react';
import { areas, components, documentationPercent, documents, evidence, facility, machines, relationships, revisions } from './facilityData';
import { FacilityArea, FacilityAsset, VerificationState } from './types/facility';

const stateLabel: Record<string, string> = { COMPLETE: 'Complete', REVIEW: 'Review', IN_PROGRESS: 'In progress', DRAFT: 'Draft', NOT_STARTED: 'Not started', VERIFIED: 'Verified', FIELD_VERIFY: 'Field verify', INFERRED: 'Inferred', DISPUTED: 'Disputed', RETIRED: 'Retired' };
const stateClass = (state: string) => state.toLowerCase().replace('_', '-');

export function TopNavigation({ query, onQuery, onOpenCabinet }: { query: string; onQuery: (value: string) => void; onOpenCabinet: () => void }) {
  return <header className="top-nav"><div className="brand"><span className="brand-mark">JL</span><strong>J. LIEB FOODS</strong><span>INDUSTRIAL ASSET GRAPH</span></div><nav aria-label="Primary"><button className="nav-active">Dashboard</button><button>Assets</button><button>Documents</button><button onClick={onOpenCabinet}>Control cabinets</button></nav><a className="film-link" href="./presentation/" target="_blank" rel="noopener noreferrer"><strong>▶ WATCH PROJECT FILM</strong><small>See why facility knowledge is at risk and how the system works.</small></a><label className="global-search"><span className="sr-only">Search assets</span><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search assets…" /><kbd>/</kbd></label></header>;
}

export function FacilitySidebar({ selectedAreaId, onSelect, filters, onFilters }: { selectedAreaId: string | null; onSelect: (area: FacilityArea) => void; filters: Set<VerificationState>; onFilters: (filters: Set<VerificationState>) => void }) {
  const toggle = (value: VerificationState) => { const next = new Set(filters); next.has(value) ? next.delete(value) : next.add(value); onFilters(next); };
  return <aside className="facility-sidebar"><section><p className="panel-title">Facility navigation</p><button className="side-active">▦ <span>Building layout</span></button><button>⌁ <span>Areas</span><b>{areas.length}</b></button><button>⚙ <span>Equipment</span><b>{machines.length + components.length}</b></button><button>⌘ <span>Systems</span></button></section><section><p className="panel-title">Areas</p><div className="area-scroll">{areas.map((area) => <button key={area.id} className={selectedAreaId === area.id ? 'side-selected' : ''} onClick={() => onSelect(area)}><i className={`dot ${stateClass(area.status)}`} /><span>{area.shortName}</span><b>{area.assetIds.length || ''}</b></button>)}</div></section><section className="legend"><p className="panel-title">Verification filters</p>{(['VERIFIED', 'FIELD_VERIFY', 'INFERRED', 'DISPUTED', 'RETIRED'] as VerificationState[]).map((item) => <label key={item}><input type="checkbox" checked={filters.has(item)} onChange={() => toggle(item)} /><i className={`dot ${stateClass(item)}`} />{stateLabel[item]}</label>)}</section></aside>;
}

export function FacilityMap2D({ selectedArea, selectedAsset, onArea, onAsset }: { selectedArea: FacilityArea | null; selectedAsset: FacilityAsset | null; onArea: (area: FacilityArea) => void; onAsset: (asset: FacilityAsset) => void }) {
  return <section className="map-panel panel"><div className="panel-heading"><div><p className="panel-title">Building layout</p><small>{selectedArea ? selectedArea.name : 'All documented areas'}</small></div><span className="map-hint">Select an outlined area</span></div><div className="facility-map" role="group" aria-label="Interactive J. Lieb facility layout"><img src={new URL('assets/labeled-building-layout.png', document.baseURI).href} alt="Labeled building floor layout" />{areas.map((area) => <button key={area.id} className={`map-region ${selectedArea?.id === area.id ? 'selected' : ''}`} style={{ left: `${area.overlay.x}%`, top: `${area.overlay.y}%`, width: `${area.overlay.width}%`, height: `${area.overlay.height}%` }} aria-label={`${area.name}, ${stateLabel[area.status]}, ${area.assetIds.length} assets`} onClick={() => onArea(area)}><span className={`dot ${stateClass(area.status)}`} /></button>)}{selectedArea?.assetIds.map((id, index) => { const asset = machines.find((item) => item.id === id); return asset ? <button key={id} className={`machine-marker ${selectedAsset?.id === id ? 'selected' : ''}`} style={{ left: `${43 + index * 15}%`, top: `${60 + (index % 2) * 12}%` }} onClick={() => onAsset(asset)}><span>⚙</span><b>{asset.id}</b><small>{asset.name}</small></button> : null; })}</div><div className="map-legend"><span><i className="dot complete" />Complete</span><span><i className="dot in-progress" />In progress</span><span><i className="dot not-started" />Not started</span><span className="context-note">Markers are area-level references; exact positions require field verification.</span></div></section>;
}

function FactRow({ label, fact }: { label: string; fact: { value: string | number | null; unit?: string; verificationStatus: VerificationState; note?: string } }) { return <div className="fact-row"><dt>{label}</dt><dd>{fact.value ?? 'Unknown'}{fact.unit ? ` ${fact.unit}` : ''}<span className={`fact-state ${stateClass(fact.verificationStatus)}`} title={fact.note}>{stateLabel[fact.verificationStatus]}</span></dd></div>; }

export function SelectedAssetPanel({ asset, activeDocument, onDocument, onOpenCabinet }: { asset: FacilityAsset | null; activeDocument: string | null; onDocument: (id: string) => void; onOpenCabinet: () => void }) {
  if (!asset) return <aside className="asset-panel panel empty-state"><div><span className="empty-icon">⌁</span><h2>Select an asset</h2><p>Choose Warehouse F, then select the machine marker to open its evidence-aware documentation package.</p></div></aside>;
  const assetDocs = documents.filter((item) => item.assetId === asset.id); const active = assetDocs.find((item) => item.id === activeDocument);
  return <aside className="asset-panel panel"><div className="asset-banner"><div><p>Selected asset</p><h2>{asset.id}</h2><span>{asset.name}</span></div><span className={`verification-badge ${stateClass(asset.verificationStatus)}`}>{stateLabel[asset.verificationStatus]}</span></div><div className="asset-panel-scroll">{asset.id === 'L2-CC-001' && <button className="open-cabinet-cta" onClick={onOpenCabinet}><span>▥</span><b>OPEN INTERACTIVE CABINET</b><small>Inspect all 50 indexed devices →</small></button>}<dl className="identity-grid"><FactRow label="Location" fact={{ value: `${areas.find((item) => item.id === asset.areaId)?.name} / ${asset.line}`, verificationStatus: asset.id === 'L2-CC-001' ? 'INFERRED' : 'VERIFIED', note: asset.id === 'L2-CC-001' ? 'Area association is provisional; exact field location is not yet verified.' : undefined }} /><FactRow label="Asset type" fact={{ value: asset.type, verificationStatus: 'VERIFIED' }} /><FactRow label="Manufacturer" fact={asset.manufacturer} /><FactRow label="Model" fact={asset.model} /><FactRow label="Serial" fact={asset.serialNumber} />{asset.facts.map((item) => <FactRow key={item.label} label={item.label} fact={item.value} />)}</dl><div className="progress-header"><span>Documentation progress</span><b>{documentationPercent(asset.id)}%</b></div><progress value={documentationPercent(asset.id)} max="100" />{active ? <section className="document-detail"><button onClick={() => onDocument('')} aria-label="Close documentation detail">×</button><p className="panel-title">{active.category}</p><h3>{active.title}</h3><p>Status: <strong>{stateLabel[active.state]}</strong></p><p>{active.verificationStatus === 'VERIFIED' ? 'Indexed content is tied to the approved cabinet reference package.' : active.verificationStatus === 'INFERRED' ? 'Working document; content requires review before it can be treated as verified.' : 'Required field documentation has not yet been supplied.'}</p><code>{active.path}</code></section> : <div className="document-grid">{assetDocs.map((item) => <button key={item.id} onClick={() => onDocument(item.id)}><span className="doc-icon">{({ Electrical: 'ϟ', Controls: '▥', Pneumatics: '≋', Mechanical: '⚙', LOTO: '▣', Parts: '⬡', Photos: '▧' } as Record<string, string>)[item.category] ?? '◫'}</span><b>{item.category}</b><small className={stateClass(item.state)}>{stateLabel[item.state]}</small></button>)}</div>}<section className="unknowns"><p className="panel-title">Field verification queue</p>{asset.unknowns.slice(0, 5).map((item) => <p key={item}><i className="dot field-verify" />{item}</p>)}</section></div></aside>;
}

export function RelationshipPanel({ asset, onNode, onOpenCabinet }: { asset: FacilityAsset | null; onNode: (id: string) => void; onOpenCabinet: () => void }) {
  const nodes = asset ? components.filter((item) => item.parentId === asset.id) : [];
  const visibleNodes = nodes.slice(0, 8);
  return <section className="relationship-panel panel"><div className="panel-heading"><p className="panel-title">Asset relationships</p><span>{asset ? `${nodes.length} indexed components` : 'Select an asset'}</span></div>{asset ? <div className="relationship-flow"><button className="relation-root" onClick={() => onNode(asset.id)}><small>{asset.type}</small>{asset.id}</button><span className="relation-line" />{visibleNodes.map((node) => <button key={node.id} onClick={() => onNode(node.id)} className={node.type === 'VFD' ? 'electric' : 'control'}><small>{node.type.replace('_', ' ')}</small>{node.label}<i className={`dot ${stateClass(node.verificationStatus)}`} /></button>)}{nodes.length > visibleNodes.length && <button className="relationship-more" onClick={onOpenCabinet}><small>Interactive drawing</small>+{nodes.length - visibleNodes.length} more devices →</button>}</div> : <p className="muted">Relationship nodes appear after a machine is selected.</p>}</section>;
}

export function VerificationSummary({ asset }: { asset: FacilityAsset | null }) { const items = asset ? [asset.manufacturer, asset.model, asset.serialNumber, ...asset.facts.map((item) => item.value), ...components.filter((item) => item.parentId === asset.id)] : []; const counts = (['VERIFIED', 'FIELD_VERIFY', 'INFERRED', 'DISPUTED', 'RETIRED'] as VerificationState[]).map((state) => [state, items.filter((item) => item.verificationStatus === state).length] as const); return <section className="verification-panel panel"><p className="panel-title">Verification status</p>{counts.map(([state, count]) => <div key={state}><span><i className={`dot ${stateClass(state)}`} />{stateLabel[state]}</span><b>{count}</b></div>)}<footer>Total tracked facts <strong>{items.length}</strong></footer></section>; }
export function RecentActivityPanel() { return <section className="activity-panel panel"><p className="panel-title">Recent activity</p>{revisions.map((item) => <div key={item.id}><i className="dot in-progress" /><span><b>{item.reason}</b><small>{item.changedBy} · {new Date(item.changedAt).toLocaleDateString()}</small></span></div>)}<div><i className="dot field-verify" /><span><b>{evidence.length} local evidence records indexed</b><small>Files remain outside the frontend bundle</small></span></div><div><i className="dot complete" /><span><b>{relationships.length} relationships validated</b><small>Evidence-aware structured data</small></span></div></section>; }

export default function Dashboard({ onOpenCabinet }: { onOpenCabinet: () => void }) {
  const params = new URLSearchParams(location.search); const initialAsset = machines.find((item) => item.id === params.get('asset')) ?? null; const initialArea = areas.find((item) => item.id === params.get('area')) ?? (initialAsset ? areas.find((item) => item.id === initialAsset.areaId) : null) ?? null;
  const [selectedArea, setSelectedArea] = useState<FacilityArea | null>(initialArea); const [selectedAsset, setSelectedAsset] = useState<FacilityAsset | null>(initialAsset); const [query, setQuery] = useState(''); const [filters, setFilters] = useState(new Set<VerificationState>(['VERIFIED', 'FIELD_VERIFY', 'INFERRED', 'DISPUTED', 'RETIRED'])); const [activeDocument, setActiveDocument] = useState<string | null>(null);
  useEffect(() => { const next = new URLSearchParams(); if (selectedArea) next.set('area', selectedArea.id); if (selectedAsset) next.set('asset', selectedAsset.id); history.replaceState(null, '', `${location.pathname}${next.size ? `?${next}` : ''}`); localStorage.setItem('industrial-asset-selection', JSON.stringify({ area: selectedArea?.id, asset: selectedAsset?.id })); }, [selectedArea, selectedAsset]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === '/' && document.activeElement?.tagName !== 'INPUT') { event.preventDefault(); document.querySelector<HTMLInputElement>('.global-search input')?.focus(); } }; addEventListener('keydown', handler); return () => removeEventListener('keydown', handler); }, []);
  const matches = useMemo(() => { const needle = query.trim().toLowerCase(); return machines.filter((asset) => filters.has(asset.verificationStatus) && (!needle || [asset.id, asset.name, asset.description, asset.type, asset.manufacturer.value, asset.model.value, ...documents.filter((doc) => doc.assetId === asset.id).map((doc) => doc.category)].join(' ').toLowerCase().includes(needle))); }, [query, filters]);
  useEffect(() => { if (query && matches.length === 1) { setSelectedAsset(matches[0]); setSelectedArea(areas.find((area) => area.id === matches[0].areaId) ?? null); } }, [matches, query]);
  const selectArea = (area: FacilityArea) => { setSelectedArea(area); setActiveDocument(null); if (!area.assetIds.includes(selectedAsset?.id ?? '')) setSelectedAsset(null); };
  return <main className="dashboard"><TopNavigation query={query} onQuery={setQuery} onOpenCabinet={onOpenCabinet} /><FacilitySidebar selectedAreaId={selectedArea?.id ?? null} onSelect={selectArea} filters={filters} onFilters={setFilters} /><div className="dashboard-content"><FacilityMap2D selectedArea={selectedArea} selectedAsset={selectedAsset} onArea={selectArea} onAsset={setSelectedAsset} /><SelectedAssetPanel asset={selectedAsset} activeDocument={activeDocument} onDocument={(id) => setActiveDocument(id || null)} onOpenCabinet={onOpenCabinet} /><RelationshipPanel asset={selectedAsset} onNode={(id) => { const machine = machines.find((item) => item.id === id); if (machine) setSelectedAsset(machine); }} onOpenCabinet={onOpenCabinet} /><VerificationSummary asset={selectedAsset} /><RecentActivityPanel /></div><footer className="facility-status"><span>Facility status <b><i className="dot complete" />{facility.status}</b></span><span>Documented assets <b>{machines.length}</b></span><span>Open field items <b>{selectedAsset?.unknowns.length ?? machines.reduce((sum, item) => sum + item.unknowns.length, 0)}</b></span><span>Evidence policy <b>Local-only protected</b></span></footer></main>;
}
